version: '3'

services:
  proxy:
    image: traefik:v2.10
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proxy/traefik.yml:/etc/traefik/traefik.yml
      - ./proxy/conf:/etc/traefik/conf
    environment:
      APP_DOMAIN: "${APP_DOMAIN}"